#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.prometheus.enabled:

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"contour"}})
---
spec:
  template:
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "metrics"
        prometheus.io/path: "/metrics"

#@overlay/match by=overlay.subset({"kind":"DaemonSet","metadata":{"name":"envoy"}}), expects="0+"
---
spec:
  template:
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "metrics"
        prometheus.io/path: "/stats/prometheus"

#@ end
